I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 107, in script
    return
Exception: Could not find return label (u'C:\\Users\\Thomas\\OneDrive\\Documents\\VN\\VN_Veleda\\VN_Veleda/game/taverne.rpy', 1495543278, 26).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 107, in script
    return
  File "D:\RenPy\renpy-6.99.12.4-sdk\renpy\ast.py", line 1376, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "D:\RenPy\renpy-6.99.12.4-sdk\renpy\execution.py", line 552, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label (u'C:\\Users\\Thomas\\OneDrive\\Documents\\VN\\VN_Veleda\\VN_Veleda/game/taverne.rpy', 1495543278, 26).

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Véléda - Pour Josiane et ces chers Germains 0.5
