I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/screens.rpy", line 1496, in script
    
Exception: Sayer 'gr' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/screens.rpy", line 1496, in script
    
  File "D:\RenPy\renpy-6.99.12.4-sdk\renpy\ast.py", line 593, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\RenPy\renpy-6.99.12.4-sdk\renpy\ast.py", line 509, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'gr' is not defined.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Véléda - Pour Josiane et ces chers Germains 0.5
