I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/ressources.rpy", line 112, in script
    image bg_chambre = im.FactorScale("images/decor/Lieu_chambre.png",zoom = 0.33)
  File "game/ressources.rpy", line 112, in <module>
    image bg_chambre = im.FactorScale("images/decor/Lieu_chambre.png",zoom = 0.33)
TypeError: __init__() takes at least 3 arguments (2 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\Programs\Renpy\renpy-6.99.12.4-sdk\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "D:\Programs\Renpy\renpy-6.99.12.4-sdk\renpy\main.py", line 419, in main
    game.context().run(node)
  File "game/ressources.rpy", line 112, in script
    image bg_chambre = im.FactorScale("images/decor/Lieu_chambre.png",zoom = 0.33)
  File "D:\Programs\Renpy\renpy-6.99.12.4-sdk\renpy\ast.py", line 907, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "D:\Programs\Renpy\renpy-6.99.12.4-sdk\renpy\python.py", line 1743, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/ressources.rpy", line 112, in <module>
    image bg_chambre = im.FactorScale("images/decor/Lieu_chambre.png",zoom = 0.33)
TypeError: __init__() takes at least 3 arguments (2 given)

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Véléda - Pour Josiane et ces chers Germains 0.6
