I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 107, in script
    return
Exception: Could not find return label (u'D:\\Projects\\VN\\GIt\\Veleda_Git\\VN_Veleda/game/script.rpy', 1496842587, 10).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 107, in script
    return
  File "D:\Programs\Renpy\renpy-6.99.12.4-sdk\renpy\ast.py", line 1376, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "D:\Programs\Renpy\renpy-6.99.12.4-sdk\renpy\execution.py", line 552, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label (u'D:\\Projects\\VN\\GIt\\Veleda_Git\\VN_Veleda/game/script.rpy', 1496842587, 10).

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Véléda - Pour Josiane et ces chers Germains 0.6
